# Build script
environment:
  gittoken: x6YxKDuSsTSAWxLt5H/M90M3K+zWin842d9AkUYMwTX1TpB65jHHVjAqd2VHmTqR

init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Branches to build
#branches:
#  # Whitelist
#  only:
#    - develop
#    - master
