# Build script
version: 1.0.{build}
environment:
  MYGET_API_KEY: 3cfd8565-9202-4b39-a7a8-ef7d784fcf2e
  gittoken:
    secure: x6YxKDuSsTSAWxLt5H/M90M3K+zWin842d9AkUYMwTX1TpB65jHHVjAqd2VHmTqR

init:
  - git config --global core.autocrlf true

# Build script
build_script:
- ps: ./Build.ps1 -target "AppVeyor"

# Tests
test: off

# Branches to build
#branches:
#  # Whitelist
#  only:
#    - develop
#    - master
